### ISSUE TITLE
Section.find fails error loading data

### ISSUE THREAD

**Issue by myTselection** [myTselection/MyEnergy#7]
Exception thrown and sensor not updated/loaded

**Comment by tjorim** [comment]
Since when did you notice this? I did not check my logs in a while. Sometime after noon on October 2nd?
I had a rather high CPU usage for a few days and bdraco looked at a callgrind with these standing out:
- </usr/local/lib/python3.11/site-packages/xbox/webapi/api/provider/people/init.py>
- /config/custom_components/myenergy/sensor.py
- and hassio updating addons

**Comment by myTselection** [comment]
Yes I noticed the same high CPU and also temporarly disabled myenergy. I see now it's caused by a new website design... so I'll need to redo part of the reverse engineering.

**Comment by myTselection** [comment]
should be fixed as of R2.0
